Repository KUSITMS-30th-TEAM-C/frontend, pull requests merged in 2024-11, with the labels that each got.

#14 feat: axios, 데이터페칭 환경설정 및 빠른시작 api 연결
  package-lock.json
  package.json
  src/api/core.ts
  src/api/index.ts
  src/api/types.ts
  src/app/home/api/api.ts
  src/app/home/api/queries.ts
  src/app/home/api/type.ts
  src/app/home/fast/add/page.tsx
  src/app/home/fast/components/FastCard.tsx
  src/app/home/fast/components/Fetcher.tsx
  src/app/home/fast/page.tsx
  src/app/home/layout.tsx
  src/app/layout.tsx
  src/app/start/components/Step1.tsx
  src/app/start/components/Step2.tsx
  src/app/start/components/Step3.tsx
  src/app/start/components/Step4.tsx
  src/components/common/Input/useInput.ts
  src/constants/api.ts
  src/constants/index.ts
  src/hooks/index.tsx
  src/hooks/useIsClient.ts
  src/lib/QueryProvider.tsx
  src/lib/getQueryClient.tsx
  src/lib/index.tsx
  src/react-utils/AsyncBoundary/index.tsx
  src/react-utils/ErrorBoundary/ErrorBoundaryContext.tsx
  src/react-utils/ErrorBoundary/index.tsx
  src/react-utils/SSRSafeSuspense/index.tsx
  src/react-utils/generateContext/index.tsx
  src/react-utils/index.tsx
  src/store/useUserInfo.ts
Labels: feature

#19 [refactor] axios 에러 응답 수정 및 온보딩 api 연결 로직 리팩토링
  src/api/core.ts
  src/app/home/page.tsx
  src/app/start/api/api.ts
  src/app/start/api/type.ts
  src/app/start/components/Step1.tsx
  src/app/start/components/Step2.tsx
  src/app/start/components/Step3.tsx
  src/app/start/components/Step4.tsx
  src/app/start/page.tsx
  src/components/Icons/Caution.tsx
  src/components/Icons/Clock.tsx
  src/components/Icons/Logo.tsx
  src/components/Icons/Pencil.tsx
  src/components/Icons/Plus.tsx
  src/store/useUserInfo.ts
Labels: enhancement

#21 [Feat] 아카이빙 캘린더, 컴포넌트 깜빡임 대응
  package-lock.json
  package.json
  src/app/archive/api/fetcher.tsx
  src/app/archive/api/index.tsx
  src/app/archive/api/queries.ts
  src/app/archive/api/types.tsx
  src/app/archive/components/Activities.tsx
  src/app/archive/components/ArchiveTotal.tsx
  src/app/archive/components/Calendar/Calendar.tsx
  src/app/archive/components/Calendar/useCalendar.tsx
  src/app/archive/components/CalendarView.tsx
  src/app/archive/components/OverviewHeader.tsx
  src/app/archive/page.tsx
  src/app/globals.css
  src/app/home/page.tsx
  src/components/Icons/Clock.tsx
  src/components/Icons/IconLeft.tsx
  src/components/Icons/IconRight.tsx
  src/components/Icons/Left.tsx
  src/components/Icons/index.tsx
  src/components/common/TabList/index.tsx
  src/components/common/index.tsx
  src/components/ui/HeaderWithBack.tsx
  src/components/ui/HomeHeader.tsx
  src/lib/getQueryClient.tsx
  tailwind.config.ts
Labels: bug, enhancement, feature

#27 [feat] 홈화면 변경된 기획안 적용
  public/fonts/WavvePADO-Regular.woff2
  public/fonts/index.ts
  src/api/core.ts
  src/app/archive/page.tsx
  src/app/globals.css
  src/app/home/components/QuickBox.tsx
  src/app/home/fast/add/page.tsx
  src/app/home/fast/components/FastCard.tsx
  src/app/home/home.css
  src/app/home/hook/useQuickStart.ts
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/start/components/Step3.tsx
  src/app/start/components/Step4.tsx
  src/app/start/page.tsx
  src/app/start/start.css
  src/components/common/Badge/index.tsx
  src/components/ui/HomeHeader.tsx
  tailwind.config.ts
Labels: enhancement, feature

#35 Feat/마이페이지
  src/app/mypage/api/api.ts
  src/app/mypage/api/queries.ts
  src/app/mypage/api/types.ts
  src/app/mypage/components/fetcher.tsx
  src/app/mypage/edit/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/app/start/components/Step1.tsx
  src/app/start/components/Step3.tsx
  src/app/start/hooks/index.tsx
  src/app/start/hooks/useNicknameValidator.ts
  src/app/start/hooks/useProfileSelector.ts
  src/components/common/Switch/index.tsx
  src/components/common/index.tsx
  tailwind.config.ts
Labels: enhancement, feature

#38 [fix] 오타 수정 및 활동추천 시간 입력시 경고문구 조건부로 보여주도록 변경
  src/app/home/sg-activity/components/ChoiceSuggestions.tsx
  src/app/home/sg-activity/components/ChoiceTime.tsx
Labels: bug

#39 [fix] 뒤로가기 활성화 , 새로운 활동 추천 요청할때 남아있던 spareTime 초기화
  src/app/home/sg-activity/page.tsx
Labels: bug
